name: netherstarplugin
main: com.nicholas.Plugin
version: 1.0-SNAPSHOT
api-version: 1.21.5

permissions:
  permission.op:
    description: "Op perms to edit plugin rules"
    default: op

commands:
  command:
    description: "Starts the plugin"
    usage: "/netherstar [start]"
    aliases: [ns]
    permission: permission.op
    permission-message: "You dod not have permission to use this command"
  command:
    description: "Stops the plugin"
    usage: "/netherstar [stop]"
    aliases: [ns]
    permission: permission.op
    permission-message: "You dod not have permission to use this command"
    
