name: netherstarplugin
main: com.nicholas.NetherStar
version: 1.0-SNAPSHOT
api-version: 1.21.5

permissions:
  permission.op:
    description: "Op perms to edit plugin rules"
    default: op
  everyone:
    default: true

commands:
  netherstar:
    description: "Starts or stops the plugin"
    usage: "/<command> [start/stop]"
    aliases: [ns]
    permission: permission.op
    permission-message: "You do not have permission to use this command"
  top:
    description: "Teleports to highest block Y at current location"
    usage: "/<command>"
    aliases: [t]
    permission: everyone